apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: default
  labels:
   app: nodejs
spec:
  selector:
    matchLabels:
      run: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        run: nodejs
    spec:
      containers:
      - name: nodejs
        image: docker.registry.local:5000/nodejs:v1.${BUILD_NUMBER}

