apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: nodejs
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      run: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        run: nodejs
    spec:
      containers:
      - name: nodejs
        image: docker.registry.local:5000/nodejs:v1.42
        ports:
        - containerPort: 80

