apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: system-uat
  labels:
   app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs			
  template:
    metadata:
      labels:
        app: nodejs	
    spec:
      containers:
      - name: nodejs
        image: docker.registry.local:5000/nodejs:v1.${BUILD_NUMBER}
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: system-uat
spec:
  type: NodePort
  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 30009
  selector:
    app: nodejs
